name: Create branch on new tag in lbm-sdk

on:
  schedule:
    # Every day
    - cron: "0 1 * * *"

jobs:
  create-proto:
    runs-on: self-hosted
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
          persist-credentials: false

      - name: init submodule
        run: |
          git submodule init
          git submodule update

      - name: install dependencies
        run: yarn install

      - name: Check new tag released
        run: |
          CURRENT_TAG=$(git describe --tags --abbrev=0)
          cd ./lbm-sdk
          if [ $CURRENT_TAG != "$(git describe --tags --abbrev=0)" ]; then echo "NEW_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV; fi

      - name: Install protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.14.0'

      - name: generate proto
        if: env.NEW_TAG
        run: |
          yarn codegen
          yarn build

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Automated bump up ${{ env.NEW_TAG }}
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          branch: auto-bump-up/${{ env.NEW_TAG }}
          labels: automated pr
          title: pulling ${{ github.ref }} into main