name: Publish to NPM
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Push events to matching v*, i.e. v1.0, v20.15.10
      - "v[0-9]+.[0-9]+.[0-9]+-rc*" # Push events to matching v*, i.e. v1.0-rc1, v20.15.10-rc5
  release:
    types: [released]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      working-directory: ./js
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"
      - run: if [ ! -x "$(command -v yarn)" ]; then npm install -g yarn; fi

      - name: Install dependencies
        working-directory: ${{ env.working-directory }}
        run: |
          yarn cache clean --all
          yarn install

      - name: Build
        working-directory: ${{ env.working-directory }}
        run: yarn run build

      - name: Prepare publish
        working-directory: ${{ env.working-directory }}
        run: yarn prepare

      - name: Check if tag and version match
        working-directory: ${{ env.working-directory }}
        run: |
          if [ "$(git tag --points-at ${{ github.sha }})" == "v$(jq -r .version package.json)" ]; then
            echo "Tag and version match. Proceeding with publish."
          else
            echo "Tag and version do not match. Skipping publish."
            exit 1
          fi

      - name: Publish to NPM
        working-directory: ${{ env.working-directory }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
